# Generated by Django 3.1 on 2020-08-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('TO', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home')], default='FA', max_length=2),
        ),
    ]
