# Generated by Django 3.1 on 2020-08-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_user_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auctions.auction_listing'),
        ),
    ]
