# Generated by Django 3.1 on 2020-08-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200826_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='auction_listing',
            name='watcher',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auctions.auction_listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='auctions.Auction_listing'),
        ),
    ]
